version: '3.1'

services: 
  opiniones: #opiniones api
    build: OpinionesApi
    image: opiniones-api:2.0
    restart: always
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
  

  mongo: #instance mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express: #gestor web para esa instancia local de mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment: #usuario administrador, contraseña y cadena de conexion de mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  restaurantes-rest:
    build: 
      dockerfile: ./Dockerfile
    image: restaurantes-rest:2.0
    restart: always
    ports:
      - 8080:8080

  pasarela:
    build:
      dockerfile: ./Dockerfile2
    image: pasarela:2.0
    restart: always
    ports:
      - 8090:8090

